# Generated by Django 6.0.1 on 2026-04-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0002_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='total_students',
            field=models.IntegerField(default=0),
        ),
    ]
