# Generated by Django 6.0.1 on 2026-04-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0003_department_total_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('institute_id', models.AutoField(primary_key=True, serialize=False)),
                ('institute_name', models.CharField(max_length=200)),
            ],
        ),
    ]
