# Generated by Django 6.0.1 on 2026-04-17 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0006_alter_department_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='coord_name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='hod_name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='total_students',
        ),
    ]
