# Generated by Django 6.0.1 on 2026-04-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0007_remove_department_coord_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='code',
        ),
    ]
