# Generated by Django 6.0.2 on 2026-03-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0002_student_course_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
